require 'pry'
require_relative '../lib/triangle'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
 t1 = Triangle.new(1, 2, 3)
 t2 = Triangle.new(0.4, 0.6, 0.3)
 t3 = Triangle.new(0, 0, 0)


RSpec.configure do |config|
# binding.pry
0
end
